#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("krishisevak.Resource", IsApplication=true)]

namespace krishisevak
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int booking = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int favourite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int home = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int images = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int information = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logosmall = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logout = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int profile = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int scheme = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int status = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int titile = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int titlenew = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int booking = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int bookinginfo = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int favourite = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int favouriteprofile = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int head = 2131099674;
			
			// aapt resource value: 0x7f060009
			public const int homebar = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int homeicon = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int hometext = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int information = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int lastdate = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int lastdates = 2131099679;
			
			// aapt resource value: 0x7f060004
			public const int loginbtn = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int logo = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int logobar = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int logout = 2131099655;
			
			// aapt resource value: 0x7f06001e
			public const int maxs = 2131099678;
			
			// aapt resource value: 0x7f06000c
			public const int noti = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int password = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int profile = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int scheme = 2131099662;
			
			// aapt resource value: 0x7f060018
			public const int schemedesc = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int schemedescs = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int schemelist = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int schemename = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int schemenames = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int schemeno = 2131099675;
			
			// aapt resource value: 0x7f06000d
			public const int schemenoti = 2131099661;
			
			// aapt resource value: 0x7f060025
			public const int scpass = 2131099685;
			
			// aapt resource value: 0x7f060022
			public const int sid = 2131099682;
			
			// aapt resource value: 0x7f060005
			public const int signup = 2131099653;
			
			// aapt resource value: 0x7f060020
			public const int signupid = 2131099680;
			
			// aapt resource value: 0x7f060026
			public const int smobile = 2131099686;
			
			// aapt resource value: 0x7f060021
			public const int sname = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int spass = 2131099684;
			
			// aapt resource value: 0x7f06000f
			public const int status = 2131099663;
			
			// aapt resource value: 0x7f060027
			public const int submit = 2131099687;
			
			// aapt resource value: 0x7f060008
			public const int title = 2131099656;
			
			// aapt resource value: 0x7f060023
			public const int uid = 2131099683;
			
			// aapt resource value: 0x7f060002
			public const int username = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int first = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Scheme = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int schemelists = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int schemerequest = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int signup = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Fulle = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
